ALTER TABLE "Tournament"
  ADD COLUMN "infoViewTab" TEXT NOT NULL DEFAULT 'PLAYERS',
  ADD COLUMN "infoViewPage" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "TournamentSettings"
  ADD COLUMN "rulesMode" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "rulesWinConditions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "rulesSummoners" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "rulesExtraInfo" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
